### PR TITLE
feat/use kimchima chat_summary to gernarate_answer

### PR DESCRIPTION
**Pull request by Micost**
**Description**

This PR update the chat method and text generation logic by using kimchima .  <strike>Hold on this PR and keep is not merged until all in the same page</strike></p>  This PR is ready to merge.

**Notes for Reviewers**

**[Signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
@Micost How about I change the function body that we do not need to init pipeline for every time. And then we fix the issue in this PR.

**Comment by Micost** [comment]
@Aisuko update the code with async init pipeline when backend start

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
#116

**Pull request merged**
