### PR TITLE
Signing fixed, added requirements.txt initial implementation.

### PR DESCRIPTION
**Pull request by CarterFaceySmith**
**Description**

This PR adds a baseline requirements.txt which can be updated to reflect any incoming dev dependencies in future.

**Notes for Reviewers**
My commits should now be signed.

**[Signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
Hi, @Micost. May you help us to confirm we only use these two libs when do the coding tasks?

**Review by Micost — CHANGES_REQUESTED** [review]
LGTM

**Comment by Micost** [comment]
Hold and let me run a test

**Review by Micost — DISMISSED** [review]
LGTM, there two libs are good for test

**Comment by Aisuko** [comment]
@Micost thank you. Do we need others?

**Comment by Micost** [comment]
Pytest-cov is also helpful. I think we can increase the requirement.txt base on request, there is no need to add them all at one time

**Comment by CarterFaceySmith** [comment]
Added commit to standardize the logging system to use loguru as per open issue [#130](https://github.com/SkywardAI/chat-backend/issues/130). Please review for merging.

**Comment by Aisuko** [comment]
Hi @Micost. @CarterFaceySmith added `log` by using `loguru`. Please help us to review the code. Thanks.

**Review by Micost — APPROVED** [review]
LGTM

**Pull request merged**
